openapi: 3.1.0
info:
  title: nbcamp 일정 관리 앱
  description: 일정 관리 앱 API 문서입니다.
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Schedule Controller
  description: 일정에 대한 CRUD를 담당합니다.
paths:
  /schedules:
    get:
      tags:
      - Schedule Controller
      operationId: getSchedules
      parameters:
      - name: search
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/ScheduleSearch"
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 1
          minimum: 1
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
          minimum: 1
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageScheduleResponseDto"
    post:
      tags:
      - Schedule Controller
      operationId: createSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleCreateDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: integer
                format: int64
  /schedules/{scheduleId}:
    get:
      tags:
      - Schedule Controller
      operationId: getSchedule
      parameters:
      - name: scheduleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ScheduleResponseDto"
    delete:
      tags:
      - Schedule Controller
      operationId: removeSchedule
      parameters:
      - name: scheduleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PasswordRequest"
        required: true
      responses:
        "200":
          description: OK
    patch:
      tags:
      - Schedule Controller
      operationId: updateSchedule
      parameters:
      - name: scheduleId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScheduleUpdateDto"
        required: true
      responses:
        "200":
          description: OK
components:
  schemas:
    AuthorRequestDto:
      type: object
      properties:
        authorName:
          type: string
          minLength: 1
        email:
          type: string
      required:
      - authorName
    ScheduleCreateDto:
      type: object
      properties:
        author:
          $ref: "#/components/schemas/AuthorRequestDto"
        content:
          type: string
          maxLength: 200
          minLength: 0
        password:
          type: string
          minLength: 1
      required:
      - content
      - password
    ScheduleUpdateDto:
      type: object
      properties:
        content:
          type: string
        authorName:
          type: string
        password:
          type: string
          minLength: 1
      required:
      - password
    ScheduleSearch:
      type: object
      properties:
        authorId:
          type: integer
          format: int64
        updatedAt:
          type: string
          format: date
    PageScheduleResponseDto:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/ScheduleResponseDto"
        page:
          type: integer
          format: int32
        size:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
    ScheduleResponseDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        authorId:
          type: integer
          format: int64
        content:
          type: string
        authorName:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    PasswordRequest:
      type: object
      properties:
        password:
          type: string
          minLength: 1
      required:
      - password
